# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-05 15:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_admin', '0003_auto_20170605_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='news',
            field=models.ManyToManyField(blank=True, to='my_admin.News'),
        ),
    ]
